language: php

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

## Test with different dependencies
#env:
#  - DEPENDENCIES=acme/package:^1.0
#  - DEPENDENCIES=acme/package:^2.0

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
      env: DEPENDENCIES=satooshi/php-coveralls:~1.0 COVERAGE_FLAGS="--coverage-clover coverage.xml"

before_install:
  - if [ "$DEPENDENCIES" != "" ]; then composer require --no-update $DEPENDENCIES; fi;

install: composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit $COVERAGE_FLAGS

after_script:
  - if [ "$COVERAGE_FLAGS" != "" ]; then vendor/bin/coveralls -v; fi

